// This code was generated by the Codegen feature of playwright
import { test, expect } from "@playwright/test";
test("Successful login", async ({ page }) => {
  // Navigste to the web page
  await page.goto("https://the-internet.herokuapp.com/login");

  // Fill in the useer fields and login
  await page.getByLabel("Username").click();
  await page.getByLabel("Username").fill("tomsmith");
  await page.getByLabel("Password").click();
  await page.getByLabel("Password").fill("SuperSecretPassword!");
  await page.getByRole("button", { name: " Login" }).click();

  // Check visibility of login message
  await expect(page.locator("html")).toBeVisible();

  // Check login message text
  await expect(page.locator("h4")).toContainText(
    "Welcome to the Secure Area. When you are done click logout below."
  );
  await page.locator("html").click();

  await page.pause();
});
